# Generated by Django 3.0.6 on 2020-07-17 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200717_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_user',
            name='blog_post',
        ),
        migrations.DeleteModel(
            name='blog_item',
        ),
        migrations.DeleteModel(
            name='blog_user',
        ),
    ]
